# Generated by Django 4.2 on 2023-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='auction_value',
            field=models.IntegerField(default=0),
        ),
    ]
